version: 1.0.0

# Development Standards Configuration
standards:
  commit_pattern:
    format: "<type>: <description> [<reference>]"
    types:
      - feat
      - fix
      - docs
      - style
      - refactor
      - test
      - chore
    references:
      wip: "refs #<issue>:"
      completion:
        - "fixes #<issue>:"
        - "closes #<issue>:"
        - "resolves #<issue>:"

  branch_pattern:
    format: "<type>/<issue-number>_<description>"
    separator: "_"
    types:
      - feat
      - fix
      - docs
      - style
      - refactor
      - test
      - chore

# AI Assistant Configuration
ai_preferences:
  code_style: "clean and documented"
  documentation_style: "detailed with examples"
  response_format: "concise and actionable"
  primary_focus:
    - code quality
    - user privacy
    - educational value
