# AI Configuration Settings - Machine-readable preferences for AI tools

# Project Preferences
project:
  name: "Lightweight Spring Actuator Monitor"
  type: "single-file-application"
  primary_language: "javascript"
  architecture: "standalone"

# Code Style
style:
  javascript:
    format: "es6+"
    strict_mode: true
    prefer_const: true
    max_line_length: 100

  html:
    format: "html5"
    semantic: true
    accessibility: true

  css:
    methodology: "bem"
    responsive: true
    mobile_first: true

# Documentation
documentation:
  language: "en"
  tone: "technical_friendly"
  include_examples: true
  code_comments: true
  update_screenshots: true

# Security
security:
  cors_required: "optional"
  secure_defaults: true
  sanitize_input: true
  production_guidelines: true

# Performance
performance:
  max_refresh_rate: 5000
  debounce_inputs: true
  optimize_dom: true
  cache_selectors: true

# Browser Support
browsers:
  minimum_support:
    chrome: "last 2 versions"
    firefox: "last 2 versions"
    safari: "last 2 versions"
    edge: "last 2 versions"

# Development
development:
  linting: true
  formatting: true
  browser_testing: true
  accessibility_testing: true

# Features
features:
  metric_types:
    - memory
    - cpu
    - threads
    - garbage_collection
  auto_refresh: true
  educational_content: true
  responsive_design: true
